/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Lizardsking (https://sketchfab.com/lizardsking)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/543-ring-4c55eacf1f264799b5a61126678f8360
Title: 543 - Ring
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber';
import { Color } from 'three';

export function Inel(props) {
  const { nodes, materials } = useGLTF('/models/inel/scene.gltf')
  const groupRef = useRef();
  const { scene } = useThree();
  React.useEffect(() => {
    const silverColor = new Color(0xC0C0C0); // Hex code for silver color
    const material = materials['Scene_-_Root'];

    if (material) {
      material.color = silverColor;
      material.metalness = 1; // Increase metalness for a more metallic look
      material.roughness = 0.3; // Adjust roughness as needed
    }
  }, [materials]);

  useFrame(() => {
    if (groupRef.current) {
      groupRef.current.rotation.y += 0.01; // Ajustează viteza de rotație după necesități
    }
  });

  return (
    <group {...props} ref={groupRef} dispose={null}>
      <group position={[-3.456, 0.116, 0.361]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object004__0.geometry}
          material={materials['Scene_-_Root']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object004__0_1.geometry}
          material={materials['Scene_-_Root']}
        />
      </group>
      <group position={[0, 0.116, 0.361]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object005__0.geometry}
          material={materials['Scene_-_Root']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object005__0_1.geometry}
          material={materials['Scene_-_Root']}
        />
      </group>
      <group position={[0, 0.116, -0.361]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object006__0.geometry}
          material={materials['Scene_-_Root']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object006__0_1.geometry}
          material={materials['Scene_-_Root']}
        />
      </group>
      <group position={[3.456, 0.116, -0.361]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object007__0.geometry}
          material={materials['Scene_-_Root']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object007__0_1.geometry}
          material={materials['Scene_-_Root']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001__0.geometry}
        material={materials['Scene_-_Root']}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LineVenz00__0.geometry}
        material={materials['Scene_-_Root']}
        position={[0.864, 0.175, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LineVenz03__0.geometry}
        material={materials['Scene_-_Root']}
        position={[2.592, 0.175, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LineVenz02__0.geometry}
        material={materials['Scene_-_Root']}
        position={[-2.592, 0.175, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LineVenz01__0.geometry}
        material={materials['Scene_-_Root']}
        position={[-0.864, 0.175, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane008__0.geometry}
        material={materials['Scene_-_Root']}
        position={[0.864, 0.175, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane009__0.geometry}
        material={materials['Scene_-_Root']}
        position={[2.592, 0.175, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane010__0.geometry}
        material={materials['Scene_-_Root']}
        position={[1.728, 0.175, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane011__0.geometry}
        material={materials['Scene_-_Root']}
        position={[0, 0.175, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012__0.geometry}
        material={materials['Scene_-_Root']}
        position={[3.456, 0.175, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane013__0.geometry}
        material={materials['Scene_-_Root']}
        position={[-1.728, 0.175, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane014__0.geometry}
        material={materials['Scene_-_Root']}
        position={[-3.456, 0.175, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane015__0.geometry}
        material={materials['Scene_-_Root']}
        position={[-0.864, 0.175, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane016__0.geometry}
        material={materials['Scene_-_Root']}
        position={[-2.592, 0.175, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/models/inel/scene.gltf')