/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf --transform
Author: Yuki (https://sketchfab.com/SHLER)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/appearance-effect-light-beam-12db0ae299d140a5bd080d30dc123ef4
Title: Appearance effect light beam
*/

import React, { useRef,useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Light(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/light/scene-transformed.glb')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    if (actions && actions['Take 001']) {
      actions['Take 001'].play();
      actions['Take 001'].timeScale = 0.15;
    } else {
      console.warn('Take 001 action not found');
    }
  }, [actions]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2.1, 0, 0]} scale={25}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Xingguang_0">
                <group name="Quad_1" scale={0.01}>
                  <mesh name="Object_5" geometry={nodes.Object_5.geometry} material={materials.xingguang} />
                </group>
                <group name="Quad_(2)_2" position={[0.01, 0, -0.03]} scale={0.01}>
                  <mesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.xingguang} />
                </group>
                <group name="Quad_(3)_3" position={[-0.01, 0, -0.03]} scale={0.01}>
                  <mesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.xingguang} />
                </group>
                <group name="Quad_(4)_4" position={[-0.03, 0, -0.01]} scale={0.01}>
                  <mesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.xingguang} />
                </group>
                <group name="Quad_(5)_5" position={[-0.03, 0, 0.01]} scale={0.01}>
                  <mesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.xingguang} />
                </group>
                <group name="Quad_(6)_6" position={[0.02, 0, -0.01]} scale={0.01}>
                  <mesh name="Object_15" geometry={nodes.Object_15.geometry} material={materials.xingguang} />
                </group>
                <group name="Quad_(7)_7" position={[0.02, 0, 0.01]} scale={0.01}>
                  <mesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials.xingguang} />
                </group>
                <group name="Quad_(8)_8" position={[-0.01, 0, 0.01]} scale={0.01}>
                  <mesh name="Object_19" geometry={nodes.Object_19.geometry} material={materials.xingguang} />
                </group>
                <group name="Quad_(9)_9" position={[0.01, 0, 0.02]} scale={0.01}>
                  <mesh name="Object_21" geometry={nodes.Object_21.geometry} material={materials.xingguang} />
                </group>
                <group name="Quad_(10)_10" position={[0.02, 0, -0.03]} scale={0.01}>
                  <mesh name="Object_23" geometry={nodes.Object_23.geometry} material={materials.xingguang} />
                </group>
                <group name="Quad_(11)_11" position={[0, 0, -0.05]} scale={0.01}>
                  <mesh name="Object_25" geometry={nodes.Object_25.geometry} material={materials.xingguang} />
                </group>
                <group name="Quad_(12)_12" position={[-0.03, 0, -0.03]} scale={0.01}>
                  <mesh name="Object_27" geometry={nodes.Object_27.geometry} material={materials.xingguang} />
                </group>
                <group name="Quad_(13)_13" position={[-0.04, 0, 0]} scale={0.01}>
                  <mesh name="Object_29" geometry={nodes.Object_29.geometry} material={materials.xingguang} />
                </group>
                <group name="Quad_(14)_14" position={[-0.04, 0, 0.01]} scale={0.01}>
                  <mesh name="Object_31" geometry={nodes.Object_31.geometry} material={materials.xingguang} />
                </group>
                <group name="Quad_(15)_15" position={[-0.03, 0, 0.02]} scale={0.01}>
                  <mesh name="Object_33" geometry={nodes.Object_33.geometry} material={materials.xingguang} />
                </group>
                <group name="Quad_(16)_16" position={[-0.02, 0, 0.03]} scale={0.01}>
                  <mesh name="Object_35" geometry={nodes.Object_35.geometry} material={materials.xingguang} />
                </group>
                <group name="Quad_(17)_17" position={[0.02, 0, 0.03]} scale={0.01}>
                  <mesh name="Object_37" geometry={nodes.Object_37.geometry} material={materials.xingguang} />
                </group>
                <group name="Quad_(18)_18" position={[0, 0, 0.03]} scale={0.01}>
                  <mesh name="Object_39" geometry={nodes.Object_39.geometry} material={materials.xingguang} />
                </group>
                <group name="Quad_(19)_19" position={[0.04, 0, 0.01]} scale={0.01}>
                  <mesh name="Object_41" geometry={nodes.Object_41.geometry} material={materials.xingguang} />
                </group>
                <group name="Quad_(20)_20" position={[0.04, 0, -0.01]} scale={0.01}>
                  <mesh name="Object_43" geometry={nodes.Object_43.geometry} material={materials.xingguang} />
                </group>
                <group name="Quad_(21)_21" position={[0.05, 0, -0.03]} scale={0.01}>
                  <mesh name="Object_45" geometry={nodes.Object_45.geometry} material={materials.xingguang} />
                </group>
                <group name="Quad_(22)_22" position={[0.02, 0, -0.06]} scale={0.01}>
                  <mesh name="Object_47" geometry={nodes.Object_47.geometry} material={materials.xingguang} />
                </group>
                <group name="Quad_(23)_23" position={[-0.02, 0, -0.05]} scale={0.01}>
                  <mesh name="Object_49" geometry={nodes.Object_49.geometry} material={materials.xingguang} />
                </group>
                <group name="Quad_(24)_24" position={[-0.04, 0, -0.03]} scale={0.01}>
                  <mesh name="Object_51" geometry={nodes.Object_51.geometry} material={materials.xingguang} />
                </group>
                <group name="shu_25" position={[0.03, 0, -0.06]} scale={0.01}>
                  <mesh name="Object_53" geometry={nodes.Object_53.geometry} material={materials.guangshu} />
                </group>
                <group name="shu_(1)_26" position={[0.01, 0, -0.06]} scale={0.01}>
                  <mesh name="Object_55" geometry={nodes.Object_55.geometry} material={materials.guangshu} />
                </group>
                <group name="shu_(2)_27" position={[0.04, 0, -0.05]} scale={0.01}>
                  <mesh name="Object_57" geometry={nodes.Object_57.geometry} material={materials.guangshu} />
                </group>
                <group name="shu_(3)_28" position={[0.06, 0, -0.03]} scale={0.01}>
                  <mesh name="Object_59" geometry={nodes.Object_59.geometry} material={materials.guangshu} />
                </group>
                <group name="shu_(4)_29" position={[0.06, 0, -0.01]} scale={0.01}>
                  <mesh name="Object_61" geometry={nodes.Object_61.geometry} material={materials.guangshu} />
                </group>
                <group name="shu_(5)_30" position={[0.06, 0, 0]} scale={0.01}>
                  <mesh name="Object_63" geometry={nodes.Object_63.geometry} material={materials.guangshu} />
                </group>
                <group name="shu_(6)_31" position={[0.06, 0, 0.03]} scale={0.01}>
                  <mesh name="Object_65" geometry={nodes.Object_65.geometry} material={materials.guangshu} />
                </group>
                <group name="shu_(7)_32" position={[0.04, 0, 0.04]} scale={0.01}>
                  <mesh name="Object_67" geometry={nodes.Object_67.geometry} material={materials.guangshu} />
                </group>
                <group name="shu_(8)_33" position={[0.02, 0, 0.05]} scale={0.01}>
                  <mesh name="Object_69" geometry={nodes.Object_69.geometry} material={materials.guangshu} />
                </group>
                <group name="shu_(9)_34" position={[0, 0, 0.05]} scale={0.01}>
                  <mesh name="Object_71" geometry={nodes.Object_71.geometry} material={materials.guangshu} />
                </group>
                <group name="shu_(10)_35" position={[-0.02, 0, 0.04]} scale={0.01}>
                  <mesh name="Object_73" geometry={nodes.Object_73.geometry} material={materials.guangshu} />
                </group>
                <group name="shu_(11)_36" position={[-0.04, 0, 0.03]} scale={0.01}>
                  <mesh name="Object_75" geometry={nodes.Object_75.geometry} material={materials.guangshu} />
                </group>
                <group name="shu_(12)_37" position={[-0.05, 0, 0.02]} scale={0.01}>
                  <mesh name="Object_77" geometry={nodes.Object_77.geometry} material={materials.guangshu} />
                </group>
                <group name="shu_(13)_38" position={[-0.05, 0, 0.02]} scale={0.01}>
                  <mesh name="Object_79" geometry={nodes.Object_79.geometry} material={materials.guangshu} />
                </group>
                <group name="shu_(14)_39" position={[-0.06, 0, 0]} scale={0.01}>
                  <mesh name="Object_81" geometry={nodes.Object_81.geometry} material={materials.guangshu} />
                </group>
                <group name="shu_(15)_40" position={[-0.06, 0, -0.01]} scale={0.01}>
                  <mesh name="Object_83" geometry={nodes.Object_83.geometry} material={materials.guangshu} />
                </group>
                <group name="shu_(16)_41" position={[-0.06, 0, -0.03]} scale={0.01}>
                  <mesh name="Object_85" geometry={nodes.Object_85.geometry} material={materials.guangshu} />
                </group>
                <group name="shu_(17)_42" position={[-0.05, 0, -0.04]} scale={0.01}>
                  <mesh name="Object_87" geometry={nodes.Object_87.geometry} material={materials.guangshu} />
                </group>
                <group name="shu_(18)_43" position={[-0.04, 0, -0.05]} scale={0.01}>
                  <mesh name="Object_89" geometry={nodes.Object_89.geometry} material={materials.guangshu} />
                </group>
                <group name="shu_(19)_44" position={[-0.02, 0, -0.06]} scale={0.01}>
                  <mesh name="Object_91" geometry={nodes.Object_91.geometry} material={materials.guangshu} />
                </group>
                <group name="shu_(20)_45" position={[-0.01, 0, -0.06]} scale={0.01}>
                  <mesh name="Object_93" geometry={nodes.Object_93.geometry} material={materials.guangshu} />
                </group>
                <group name="shu_(21)_46" position={[-0.01, 0, -0.06]} scale={0.01}>
                  <mesh name="Object_95" geometry={nodes.Object_95.geometry} material={materials.guangshu} />
                </group>
                <group name="shu_(22)_47" position={[0.02, 0, 0.05]} scale={0.01}>
                  <mesh name="Object_97" geometry={nodes.Object_97.geometry} material={materials.guangshu} />
                </group>
                <group name="jianbian1_49" rotation={[Math.PI / 2, 0, -0.6]} scale={[0.51, 0.51, 0.68]}>
                  <mesh name="Object_99" geometry={nodes.Object_99.geometry} material={materials.guangshushu1} />
                </group>
                <group name="xuanwo_50" position={[0, 0.01, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.17}>
                  <mesh name="Object_101" geometry={nodes.Object_101.geometry} material={materials.yuanhuan} />
                </group>
                <group name="xuanwo_(2)_51" position={[0, 0.01, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.17}>
                  <mesh name="Object_103" geometry={nodes.Object_103.geometry} material={materials.yuanhuan} />
                </group>
                <group name="xuanwo_(3)_52" position={[0, 0.01, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.17}>
                  <mesh name="Object_105" geometry={nodes.Object_105.geometry} material={materials.yuanhuan} />
                </group>
                <group name="jianbian1_(1)_53" rotation={[Math.PI / 2, 0, 0]} scale={[0.51, 0.51, 0.68]}>
                  <mesh name="Object_107" geometry={nodes.Object_107.geometry} material={materials.guangshushu1} />
                </group>
                <group name="jianbian1_(2)_54" rotation={[Math.PI / 2, 0, 0]} scale={[0.51, 0.51, 0.68]}>
                  <mesh name="Object_109" geometry={nodes.Object_109.geometry} material={materials.guangshushu1} />
                </group>
                <group name="Xingguang_(1)_55" position={[0.02, 0, 0]} rotation={[0, 0.92, 0]} scale={0.71}>
                  <group name="Quad_56" scale={0.01}>
                    <mesh name="Object_112" geometry={nodes.Object_112.geometry} material={materials.xingguang} />
                  </group>
                  <group name="Quad_(2)_57" position={[0.01, 0, -0.03]} scale={0.01}>
                    <mesh name="Object_114" geometry={nodes.Object_114.geometry} material={materials.xingguang} />
                  </group>
                  <group name="Quad_(3)_58" position={[-0.01, 0, -0.03]} scale={0.01}>
                    <mesh name="Object_116" geometry={nodes.Object_116.geometry} material={materials.xingguang} />
                  </group>
                  <group name="Quad_(4)_59" position={[-0.03, 0, -0.01]} scale={0.01}>
                    <mesh name="Object_118" geometry={nodes.Object_118.geometry} material={materials.xingguang} />
                  </group>
                  <group name="Quad_(5)_60" position={[-0.03, 0, 0.01]} scale={0.01}>
                    <mesh name="Object_120" geometry={nodes.Object_120.geometry} material={materials.xingguang} />
                  </group>
                  <group name="Quad_(6)_61" position={[0.02, 0, -0.01]} scale={0.01}>
                    <mesh name="Object_122" geometry={nodes.Object_122.geometry} material={materials.xingguang} />
                  </group>
                  <group name="Quad_(7)_62" position={[0.02, 0, 0.01]} scale={0.01}>
                    <mesh name="Object_124" geometry={nodes.Object_124.geometry} material={materials.xingguang} />
                  </group>
                  <group name="Quad_(8)_63" position={[-0.01, 0, 0.01]} scale={0.01}>
                    <mesh name="Object_126" geometry={nodes.Object_126.geometry} material={materials.xingguang} />
                  </group>
                  <group name="Quad_(9)_64" position={[0.01, 0, 0.02]} scale={0.01}>
                    <mesh name="Object_128" geometry={nodes.Object_128.geometry} material={materials.xingguang} />
                  </group>
                  <group name="Quad_(10)_65" position={[0.02, 0, -0.03]} scale={0.01}>
                    <mesh name="Object_130" geometry={nodes.Object_130.geometry} material={materials.xingguang} />
                  </group>
                  <group name="Quad_(11)_66" position={[0, 0, -0.05]} scale={0.01}>
                    <mesh name="Object_132" geometry={nodes.Object_132.geometry} material={materials.xingguang} />
                  </group>
                  <group name="Quad_(12)_67" position={[-0.03, 0, -0.03]} scale={0.01}>
                    <mesh name="Object_134" geometry={nodes.Object_134.geometry} material={materials.xingguang} />
                  </group>
                  <group name="Quad_(13)_68" position={[-0.04, 0, 0]} scale={0.01}>
                    <mesh name="Object_136" geometry={nodes.Object_136.geometry} material={materials.xingguang} />
                  </group>
                  <group name="Quad_(14)_69" position={[-0.04, 0, 0.01]} scale={0.01}>
                    <mesh name="Object_138" geometry={nodes.Object_138.geometry} material={materials.xingguang} />
                  </group>
                  <group name="Quad_(15)_70" position={[-0.03, 0, 0.02]} scale={0.01}>
                    <mesh name="Object_140" geometry={nodes.Object_140.geometry} material={materials.xingguang} />
                  </group>
                  <group name="Quad_(16)_71" position={[-0.02, 0, 0.03]} scale={0.01}>
                    <mesh name="Object_142" geometry={nodes.Object_142.geometry} material={materials.xingguang} />
                  </group>
                  <group name="Quad_(17)_72" position={[0.02, 0, 0.03]} scale={0.01}>
                    <mesh name="Object_144" geometry={nodes.Object_144.geometry} material={materials.xingguang} />
                  </group>
                  <group name="Quad_(18)_73" position={[0, 0, 0.03]} scale={0.01}>
                    <mesh name="Object_146" geometry={nodes.Object_146.geometry} material={materials.xingguang} />
                  </group>
                  <group name="Quad_(19)_74" position={[0.04, 0, 0.01]} scale={0.01}>
                    <mesh name="Object_148" geometry={nodes.Object_148.geometry} material={materials.xingguang} />
                  </group>
                  <group name="Quad_(20)_75" position={[0.04, 0, -0.01]} scale={0.01}>
                    <mesh name="Object_150" geometry={nodes.Object_150.geometry} material={materials.xingguang} />
                  </group>
                  <group name="Quad_(21)_76" position={[0.05, 0, -0.03]} scale={0.01}>
                    <mesh name="Object_152" geometry={nodes.Object_152.geometry} material={materials.xingguang} />
                  </group>
                  <group name="Quad_(22)_77" position={[0.02, 0, -0.06]} scale={0.01}>
                    <mesh name="Object_154" geometry={nodes.Object_154.geometry} material={materials.xingguang} />
                  </group>
                  <group name="Quad_(23)_78" position={[-0.02, 0, -0.05]} scale={0.01}>
                    <mesh name="Object_156" geometry={nodes.Object_156.geometry} material={materials.xingguang} />
                  </group>
                  <group name="Quad_(24)_79" position={[-0.04, 0, -0.03]} scale={0.01}>
                    <mesh name="Object_158" geometry={nodes.Object_158.geometry} material={materials.xingguang} />
                  </group>
                  <group name="shu_80" position={[0.03, 0, -0.06]} scale={0.01}>
                    <mesh name="Object_160" geometry={nodes.Object_160.geometry} material={materials.guangshu} />
                  </group>
                  <group name="shu_(1)_81" position={[0.01, 0, -0.06]} scale={0.01}>
                    <mesh name="Object_162" geometry={nodes.Object_162.geometry} material={materials.guangshu} />
                  </group>
                  <group name="shu_(2)_82" position={[0.04, 0, -0.05]} scale={0.01}>
                    <mesh name="Object_164" geometry={nodes.Object_164.geometry} material={materials.guangshu} />
                  </group>
                  <group name="shu_(3)_83" position={[0.06, 0, -0.03]} scale={0.01}>
                    <mesh name="Object_166" geometry={nodes.Object_166.geometry} material={materials.guangshu} />
                  </group>
                  <group name="shu_(4)_84" position={[0.06, 0, -0.01]} scale={0.01}>
                    <mesh name="Object_168" geometry={nodes.Object_168.geometry} material={materials.guangshu} />
                  </group>
                  <group name="shu_(5)_85" position={[0.06, 0, 0]} scale={0.01}>
                    <mesh name="Object_170" geometry={nodes.Object_170.geometry} material={materials.guangshu} />
                  </group>
                  <group name="shu_(6)_86" position={[0.06, 0, 0.03]} scale={0.01}>
                    <mesh name="Object_172" geometry={nodes.Object_172.geometry} material={materials.guangshu} />
                  </group>
                  <group name="shu_(7)_87" position={[0.04, 0, 0.04]} scale={0.01}>
                    <mesh name="Object_174" geometry={nodes.Object_174.geometry} material={materials.guangshu} />
                  </group>
                  <group name="shu_(8)_88" position={[0.02, 0, 0.05]} scale={0.01}>
                    <mesh name="Object_176" geometry={nodes.Object_176.geometry} material={materials.guangshu} />
                  </group>
                  <group name="shu_(9)_89" position={[0, 0, 0.05]} scale={0.01}>
                    <mesh name="Object_178" geometry={nodes.Object_178.geometry} material={materials.guangshu} />
                  </group>
                  <group name="shu_(10)_90" position={[-0.02, 0, 0.04]} scale={0.01}>
                    <mesh name="Object_180" geometry={nodes.Object_180.geometry} material={materials.guangshu} />
                  </group>
                  <group name="shu_(11)_91" position={[-0.04, 0, 0.03]} scale={0.01}>
                    <mesh name="Object_182" geometry={nodes.Object_182.geometry} material={materials.guangshu} />
                  </group>
                  <group name="shu_(12)_92" position={[-0.05, 0, 0.02]} scale={0.01}>
                    <mesh name="Object_184" geometry={nodes.Object_184.geometry} material={materials.guangshu} />
                  </group>
                  <group name="shu_(13)_93" position={[-0.05, 0, 0.02]} scale={0.01}>
                    <mesh name="Object_186" geometry={nodes.Object_186.geometry} material={materials.guangshu} />
                  </group>
                  <group name="shu_(14)_94" position={[-0.06, 0, 0]} scale={0.01}>
                    <mesh name="Object_188" geometry={nodes.Object_188.geometry} material={materials.guangshu} />
                  </group>
                  <group name="shu_(15)_95" position={[-0.06, 0, -0.01]} scale={0.01}>
                    <mesh name="Object_190" geometry={nodes.Object_190.geometry} material={materials.guangshu} />
                  </group>
                  <group name="shu_(16)_96" position={[-0.06, 0, -0.03]} scale={0.01}>
                    <mesh name="Object_192" geometry={nodes.Object_192.geometry} material={materials.guangshu} />
                  </group>
                  <group name="shu_(17)_97" position={[-0.05, 0, -0.04]} scale={0.01}>
                    <mesh name="Object_194" geometry={nodes.Object_194.geometry} material={materials.guangshu} />
                  </group>
                  <group name="shu_(18)_98" position={[-0.04, 0, -0.05]} scale={0.01}>
                    <mesh name="Object_196" geometry={nodes.Object_196.geometry} material={materials.guangshu} />
                  </group>
                  <group name="shu_(19)_99" position={[-0.02, 0, -0.06]} scale={0.01}>
                    <mesh name="Object_198" geometry={nodes.Object_198.geometry} material={materials.guangshu} />
                  </group>
                  <group name="shu_(20)_100" position={[-0.01, 0, -0.06]} scale={0.01}>
                    <mesh name="Object_200" geometry={nodes.Object_200.geometry} material={materials.guangshu} />
                  </group>
                  <group name="shu_(21)_101" position={[-0.01, 0, -0.06]} scale={0.01}>
                    <mesh name="Object_202" geometry={nodes.Object_202.geometry} material={materials.guangshu} />
                  </group>
                  <group name="shu_(22)_102" position={[0.02, 0, 0.05]} scale={0.01}>
                    <mesh name="Object_204" geometry={nodes.Object_204.geometry} material={materials.guangshu} />
                  </group>
                </group>
                <group name="Xingguang_(2)_103" position={[-0.01, 0, -0.02]} rotation={[-Math.PI, 0.98, -Math.PI]} scale={0.67}>
                  <group name="Quad_104" scale={0.01}>
                    <mesh name="Object_207" geometry={nodes.Object_207.geometry} material={materials.xingguang} />
                  </group>
                  <group name="Quad_(2)_105" position={[0.01, 0, -0.03]} scale={0.01}>
                    <mesh name="Object_209" geometry={nodes.Object_209.geometry} material={materials.xingguang} />
                  </group>
                  <group name="Quad_(3)_106" position={[-0.01, 0, -0.03]} scale={0.01}>
                    <mesh name="Object_211" geometry={nodes.Object_211.geometry} material={materials.xingguang} />
                  </group>
                  <group name="Quad_(4)_107" position={[-0.03, 0, -0.01]} scale={0.01}>
                    <mesh name="Object_213" geometry={nodes.Object_213.geometry} material={materials.xingguang} />
                  </group>
                  <group name="Quad_(5)_108" position={[-0.03, 0, 0.01]} scale={0.01}>
                    <mesh name="Object_215" geometry={nodes.Object_215.geometry} material={materials.xingguang} />
                  </group>
                  <group name="Quad_(6)_109" position={[0.02, 0, -0.01]} scale={0.01}>
                    <mesh name="Object_217" geometry={nodes.Object_217.geometry} material={materials.xingguang} />
                  </group>
                  <group name="Quad_(7)_110" position={[0.02, 0, 0.01]} scale={0.01}>
                    <mesh name="Object_219" geometry={nodes.Object_219.geometry} material={materials.xingguang} />
                  </group>
                  <group name="Quad_(8)_111" position={[-0.01, 0, 0.01]} scale={0.01}>
                    <mesh name="Object_221" geometry={nodes.Object_221.geometry} material={materials.xingguang} />
                  </group>
                  <group name="Quad_(9)_112" position={[0.01, 0, 0.02]} scale={0.01}>
                    <mesh name="Object_223" geometry={nodes.Object_223.geometry} material={materials.xingguang} />
                  </group>
                  <group name="Quad_(10)_113" position={[0.02, 0, -0.03]} scale={0.01}>
                    <mesh name="Object_225" geometry={nodes.Object_225.geometry} material={materials.xingguang} />
                  </group>
                  <group name="Quad_(11)_114" position={[0, 0, -0.05]} scale={0.01}>
                    <mesh name="Object_227" geometry={nodes.Object_227.geometry} material={materials.xingguang} />
                  </group>
                  <group name="Quad_(12)_115" position={[-0.03, 0, -0.03]} scale={0.01}>
                    <mesh name="Object_229" geometry={nodes.Object_229.geometry} material={materials.xingguang} />
                  </group>
                  <group name="Quad_(14)_117" position={[-0.04, 0, 0.01]} scale={0.01}>
                    <mesh name="Object_233" geometry={nodes.Object_233.geometry} material={materials.xingguang} />
                  </group>
                  <group name="Quad_(15)_118" position={[-0.03, 0, 0.02]} scale={0.01}>
                    <mesh name="Object_235" geometry={nodes.Object_235.geometry} material={materials.xingguang} />
                  </group>
                  <group name="Quad_(16)_119" position={[-0.02, 0, 0.03]} scale={0.01}>
                    <mesh name="Object_237" geometry={nodes.Object_237.geometry} material={materials.xingguang} />
                  </group>
                  <group name="Quad_(18)_121" position={[0, 0, 0.03]} scale={0.01}>
                    <mesh name="Object_241" geometry={nodes.Object_241.geometry} material={materials.xingguang} />
                  </group>
                  <group name="Quad_(20)_123" position={[0.04, 0, -0.01]} scale={0.01}>
                    <mesh name="Object_245" geometry={nodes.Object_245.geometry} material={materials.xingguang} />
                  </group>
                  <group name="Quad_(21)_124" position={[0.05, 0, -0.03]} scale={0.01}>
                    <mesh name="Object_247" geometry={nodes.Object_247.geometry} material={materials.xingguang} />
                  </group>
                  <group name="Quad_(23)_126" position={[-0.02, 0, -0.05]} scale={0.01}>
                    <mesh name="Object_251" geometry={nodes.Object_251.geometry} material={materials.xingguang} />
                  </group>
                  <group name="Quad_(24)_127" position={[-0.04, 0, -0.03]} scale={0.01}>
                    <mesh name="Object_253" geometry={nodes.Object_253.geometry} material={materials.xingguang} />
                  </group>
                  <group name="shu_(1)_129" position={[0.01, 0, -0.06]} scale={0.01}>
                    <mesh name="Object_257" geometry={nodes.Object_257.geometry} material={materials.guangshu} />
                  </group>
                  <group name="shu_(2)_130" position={[0.04, 0, -0.05]} scale={0.01}>
                    <mesh name="Object_259" geometry={nodes.Object_259.geometry} material={materials.guangshu} />
                  </group>
                  <group name="shu_(6)_134" position={[0.06, 0, 0.03]} scale={0.01}>
                    <mesh name="Object_267" geometry={nodes.Object_267.geometry} material={materials.guangshu} />
                  </group>
                  <group name="shu_(8)_136" position={[0.02, 0, 0.05]} scale={0.01}>
                    <mesh name="Object_271" geometry={nodes.Object_271.geometry} material={materials.guangshu} />
                  </group>
                  <group name="shu_(9)_137" position={[0, 0, 0.05]} scale={0.01}>
                    <mesh name="Object_273" geometry={nodes.Object_273.geometry} material={materials.guangshu} />
                  </group>
                  <group name="shu_(11)_139" position={[-0.04, 0, 0.03]} scale={0.01}>
                    <mesh name="Object_277" geometry={nodes.Object_277.geometry} material={materials.guangshu} />
                  </group>
                  <group name="shu_(13)_141" position={[-0.05, 0, 0.02]} scale={0.01}>
                    <mesh name="Object_281" geometry={nodes.Object_281.geometry} material={materials.guangshu} />
                  </group>
                  <group name="shu_(15)_143" position={[-0.06, 0, -0.01]} scale={0.01}>
                    <mesh name="Object_285" geometry={nodes.Object_285.geometry} material={materials.guangshu} />
                  </group>
                  <group name="shu_(18)_146" position={[-0.04, 0, -0.05]} scale={0.01}>
                    <mesh name="Object_291" geometry={nodes.Object_291.geometry} material={materials.guangshu} />
                  </group>
                  <group name="shu_(19)_147" position={[-0.02, 0, -0.06]} scale={0.01}>
                    <mesh name="Object_293" geometry={nodes.Object_293.geometry} material={materials.guangshu} />
                  </group>
                  <group name="shu_(22)_150" position={[0.02, 0, 0.05]} scale={0.01}>
                    <mesh name="Object_299" geometry={nodes.Object_299.geometry} material={materials.guangshu} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/light/scene-transformed.glb')
