/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf --transform 
Files: scene.gltf [80.78KB] > C:\Users\40722\Desktop\ali\lice\public\models\snowflake_necklace\scene-transformed.glb [2.58MB] (-3092%)
Author: powerdoge (https://sketchfab.com/powerdoge)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/snowflake-necklace-d9d312dadf14458396526cb0bd22460d
Title: Snowflake Necklace
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Pandantiv(props) {
  const { nodes, materials } = useGLTF('/models/snowflake_necklace/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <instancedMesh args={[nodes.marquise_Diamond_0.geometry, materials.Diamond, 6]} instanceMatrix={nodes.marquise_Diamond_0.instanceMatrix} />
      <instancedMesh args={[nodes.BezierCircle_Silver_0.geometry, materials.Silver, 5]} instanceMatrix={nodes.BezierCircle_Silver_0.instanceMatrix} />
      <instancedMesh args={[nodes.new_curve001_Silver_0.geometry, materials.Silver, 6]} instanceMatrix={nodes.new_curve001_Silver_0.instanceMatrix} />
      <instancedMesh args={[nodes.diamond_Diamond_0.geometry, materials.Diamond, 6]} instanceMatrix={nodes.diamond_Diamond_0.instanceMatrix} />
    </group>
  )
}

useGLTF.preload('/models/snowflake_necklace/scene-transformed.glb')
